### PR TITLE
Cylinder

### PR DESCRIPTION
**Pull request by michaelcnguyen1**

### CODE REVIEW

**Comment by jakechung42** [comment]
@Makaveli-The-Don a few things that will be to be fixed. 

- Please remove the test.txt file from the branch.
- Move the cylinder file into the model folder and remove the extra period. You can try naming it CylinderV1 if you want.
- Change the robotMNguyen folder's name to endEffector, so that we know what files are inside that folder.
- Change the name of the files inside the robotMNguyen to something more descriptive about the purpose of that folder (endEffectV1, endEffectorDrawing, etc.) so that when someone looks at your folder, they know what it is for.

Thank you.

**Review by Cr1sco — APPROVED** [review]
cool

**Comment by michaelcnguyen1** [comment]
11/1/2019

Addressed the issues Jake commented on and edited the shaft to 30 mm as Johnathan requested

**Comment by michaelcnguyen1** [comment]
Base Gear Shaft changes

**Comment by jakechung42** [comment]
Complete the shaft design then you can merge.

**Pull request closed without merging**
