### PR TITLE
Completed arm base with drawing specifications

### PR DESCRIPTION
**Pull request by yahyeegal**
Worked on the Robotic arm base, designed the pocket for the Stepper motor pocket along with brackets that will hold it in place. The base also consists of two shaft cylinders that the support gears would rest on. Used Solid works to create design of the base. Attached a specification drawing to show the dimension of the base design.

### CODE REVIEW

**Comment by jakechung42** [comment]
The height of columns for the support gear is currently too much. Maybe low it down a bit so when the support gears are attached, it will be at the same level as the servo's gear. Comment here when you have it done. I'll review it again.

**Comment by yahyeegal** [comment]
I have revised the base design and its drawing specification. I upload the files

**Comment by jakechung42** [comment]
Approved.

**Review by jakechung42 — APPROVED** [review]
Approved.

**Pull request merged**
